name: 'Terraform CI/CD for Employee App'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: 'Terraform Operations'
    runs-on: ubuntu-latest
    env:

      TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
      TF_VAR_docker_password: ${{ secrets.TF_VAR_DOCKER_PASSWORD }}
      TF_VAR_allowed_ssh_ip: ${{ secrets.TF_VAR_ALLOWED_SSH_IP }}

      AWS_REGION: ${{ vars.AWS_REGION || 'eu-west-1' }}
      TF_VAR_docker_username: ${{ vars.TF_VAR_DOCKER_USERNAME || 'bakituncer' }}
      TF_VAR_key_name: ${{ vars.TF_VAR_KEY_NAME }}
      TF_VAR_vpc_cidr: ${{ vars.TF_VAR_VPC_CIDR }}
      TF_VAR_public_subnet_cidr: ${{ vars.TF_VAR_PUBLIC_SUBNET_CIDR }}
      TF_VAR_private_subnet_cidrs: '["10.0.2.0/24","10.0.3.0/24"]'
      TF_VAR_db_name: ${{ vars.TF_VAR_DB_NAME }}
      TF_VAR_db_user: ${{ vars.TF_VAR_DB_USER }}

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.6.0'

      - name: 'Configure AWS Credentials (using Access Keys)'
        if: ${{ secrets.AWS_ACCESS_KEY_ID != '' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}


      - name: 'Configure AWS Credentials (OIDC)'
        if: ${{ secrets.AWS_ACCESS_KEY_ID == '' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::YOUR_AWS_ACCOUNT_ID:role/YOUR_GITHUB_ACTIONS_ROLE_NAME
          aws-region: ${{ env.AWS_REGION }}

      - name: 'Terraform Init'
        id: init
        run: terraform init -input=false

      - name: 'Terraform Validate'
        id: validate
        run: terraform validate -no-color

      - name: 'Terraform Plan'
        id: plan
        run: |
      - name: Upload Terraform Plan Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan
          if-no-files-found: error

      - name: 'Terraform Apply (Sadece main branch''e push olduğunda)'
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -input=false -auto-approve tfplan
